# Generated by Django 4.2.2 on 2023-09-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas_app', '0005_alter_newfeed_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to='ideas_app.userprofile')),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to='ideas_app.userprofile')),
            ],
        ),
    ]
