# Generated by Django 4.2.2 on 2023-09-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
