# Generated by Django 4.2.2 on 2023-08-28 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('user_cover_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('user_about', models.TextField(max_length=500)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_completed', models.IntegerField()),
                ('fk_user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(null=True)),
                ('experience_details', models.TextField(max_length=200)),
                ('fk_user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=20)),
                ('education_details', models.TextField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(null=True)),
                ('fk_user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=30)),
                ('fk_user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NewFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='')),
                ('post_heading', models.CharField(max_length=100)),
                ('post_details', models.TextField(max_length=500)),
                ('github_link', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=15)),
                ('fk_user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_new_feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.newfeed')),
                ('fk_user_profile_contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.userprofile')),
                ('fk_new_feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.newfeed')),
            ],
        ),
    ]
