# Generated by Django 4.2.2 on 2023-09-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0002_alter_userexperience_fk_user_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='fk_user_profile_contributor_id',
            new_name='fk_user_profile_id',
        ),
    ]
