# Generated by Django 4.2.2 on 2023-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0003_rename_fk_user_profile_contributor_id_contributor_fk_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfeed',
            name='post_image',
            field=models.ImageField(upload_to='E:\\Implementation\\Django idea\\Contribute On Ideas\\ContributeOnIdeas\\media'),
        ),
    ]
