# Generated by Django 4.2.2 on 2023-09-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0004_alter_newfeed_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfeed',
            name='post_image',
            field=models.ImageField(upload_to='new_feed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
