# Generated by Django 4.2.2 on 2023-08-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('fk_received_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='ideas_app.userprofile')),
                ('fk_send_by_user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_by', to='ideas_app.userprofile')),
            ],
        ),
    ]
